-- =========================================================
-- BASIC READS
-- =========================================================

-- 1. Show all users
SELECT * FROM users;

-- 2. Show all products
SELECT * FROM products;

-- 3. Show all orders
SELECT * FROM orders;

-- 4. Show all order items
SELECT * FROM order_items;


-- =========================================================
-- SORTING
-- =========================================================

-- 5. Show products sorted by price descending
SELECT *
FROM products
ORDER BY price DESC;

-- 6. Show products sorted by name ascending
SELECT *
FROM products
ORDER BY name ASC;

-- 7. Show latest orders first
SELECT *
FROM orders
ORDER BY created_at DESC;


-- =========================================================
-- FILTERING
-- =========================================================

-- 8. Show only Electronics products
SELECT *
FROM products
WHERE category = 'Electronics';

-- 9. Show products with stock less than 25
SELECT *
FROM products
WHERE stock < 25;

-- 10. Show only CREATED orders
SELECT *
FROM orders
WHERE status = 'CREATED';

-- 11. Show orders created by user_id = 1
SELECT *
FROM orders
WHERE user_id = 1;

-- 12. Show products with price greater than 50
SELECT *
FROM products
WHERE price > 50
ORDER BY price DESC;


-- =========================================================
-- JOINS
-- =========================================================

-- 13. Show orders with user names
SELECT
    o.id AS order_id,
    u.name AS user_name,
    u.email,
    o.status,
    o.total_amount,
    o.created_at
FROM orders o
JOIN users u ON o.user_id = u.id
ORDER BY o.id;

-- 14. Show order items with product names
SELECT
    oi.id AS order_item_id,
    oi.order_id,
    p.name AS product_name,
    p.category,
    oi.quantity,
    oi.price_at_purchase
FROM order_items oi
JOIN products p ON oi.product_id = p.id
ORDER BY oi.order_id, oi.id;

-- 15. Show complete order details:
-- order, user, product, quantity, price
SELECT
    o.id AS order_id,
    u.name AS user_name,
    p.name AS product_name,
    oi.quantity,
    oi.price_at_purchase,
    (oi.quantity * oi.price_at_purchase) AS line_total,
    o.status
FROM orders o
JOIN users u ON o.user_id = u.id
JOIN order_items oi ON o.id = oi.order_id
JOIN products p ON oi.product_id = p.id
ORDER BY o.id, p.name;

-- 16. Show all users and their orders, including users with no orders
SELECT
    u.id AS user_id,
    u.name,
    o.id AS order_id,
    o.status
FROM users u
LEFT JOIN orders o ON u.id = o.user_id
ORDER BY u.id, o.id;


-- =========================================================
-- AGGREGATION
-- =========================================================

-- 17. Count total orders per user
SELECT
    u.id,
    u.name,
    COUNT(o.id) AS total_orders
FROM users u
LEFT JOIN orders o ON u.id = o.user_id
GROUP BY u.id, u.name
ORDER BY total_orders DESC, u.name ASC;

-- 18. Total money spent by each user
SELECT
    u.id,
    u.name,
    SUM(o.total_amount) AS total_spent
FROM users u
JOIN orders o ON u.id = o.user_id
GROUP BY u.id, u.name
ORDER BY total_spent DESC;

-- 19. Total quantity sold per product
SELECT
    p.id,
    p.name,
    SUM(oi.quantity) AS total_quantity_sold
FROM products p
JOIN order_items oi ON p.id = oi.product_id
GROUP BY p.id, p.name
ORDER BY total_quantity_sold DESC, p.name ASC;

-- 20. Revenue by product category
SELECT
    p.category,
    SUM(oi.quantity * oi.price_at_purchase) AS revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.id
GROUP BY p.category
ORDER BY revenue DESC;

-- 21. Average product price by category
SELECT
    category,
    AVG(price) AS average_price
FROM products
GROUP BY category
ORDER BY average_price DESC;


-- =========================================================
-- PRACTICAL ANALYSIS QUERIES
-- =========================================================

-- 22. Highest spending user
SELECT
    u.name,
    SUM(o.total_amount) AS total_spent
FROM users u
JOIN orders o ON u.id = o.user_id
GROUP BY u.name
ORDER BY total_spent DESC
LIMIT 1;

-- 23. Orders that contain more than one distinct product
SELECT
    oi.order_id,
    COUNT(DISTINCT oi.product_id) AS distinct_products
FROM order_items oi
GROUP BY oi.order_id
HAVING COUNT(DISTINCT oi.product_id) > 1
ORDER BY oi.order_id;

-- 24. Products never ordered
SELECT
    p.id,
    p.name
FROM products p
LEFT JOIN order_items oi ON p.id = oi.product_id
WHERE oi.id IS NULL
ORDER BY p.name;

-- 25. Revenue generated by each product
SELECT
    p.name,
    SUM(oi.quantity * oi.price_at_purchase) AS revenue
FROM products p
JOIN order_items oi ON p.id = oi.product_id
GROUP BY p.name
ORDER BY revenue DESC;

-- 26. Show each order with computed total from order_items
SELECT
    o.id AS order_id,
    o.total_amount AS stored_total,
    SUM(oi.quantity * oi.price_at_purchase) AS computed_total
FROM orders o
JOIN order_items oi ON o.id = oi.order_id
GROUP BY o.id, o.total_amount
ORDER BY o.id;


